dnd-side-project/dnd-8th-3-backend

build.gradle, src/main/java/d83t/bpmbackend/config/OpenApiConfig.java, src/main/resources/application.properties
관련 내용: because no Jakarta Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.
=> fix: 자카르타관련 빈 에러 발생하여, 의존성 수정

.github/workflows/deploy.yml, Dockerfile, config/nginx/Dockerfile, config/nginx/default.conf, config/scripts/docker-install.sh, docker-compose.yml
- Docker & Github Actions 세팅
- 아직 EC2 생성 전이라서 secrets 에 등록 후, Github Actions 정상 작동합니다
=> Chore: 배포 환경 세팅

.github/workflows/deploy.yml, Dockerfile, build.gradle, src/main/resources/application.properties
=> [D83T-5] RDS 연결 및 properties 추가

docker-compose.yml
=> [D83T-5] docker hub 유저네임 변경

src/main/java/d83t/bpmbackend/exception/CustomException.java, src/main/java/d83t/bpmbackend/exception/Error.java, src/main/java/d83t/bpmbackend/exception/ErrorResponse.java, src/main/java/d83t/bpmbackend/exception/GlobalExceptionHandler.java
- 전역예외처리 컨트롤러를 추가하였습니다/
- 예외가 발생했을 경우, 커스텀 에러를 발생시켜 코드의 중복을 줄이면서 재사용성을 늘렸습니다.
=> [D83T-21] 전역 예외처리 추가

.gitignore, src/main/java/d83t/bpmbackend/base/entity/DateEntity.java, src/main/java/d83t/bpmbackend/domain/aggregate/profile/dto/ProfileDto.java, src/main/java/d83t/bpmbackend/domain/aggregate/profile/dto/ProfileRequest.java, src/main/java/d83t/bpmbackend/domain/aggregate/profile/dto/ProfileResponse.java, src/main/java/d83t/bpmbackend/domain/aggregate/profile/entity/Profile.java, src/main/java/d83t/bpmbackend/domain/aggregate/profile/service/ProfileImageService.java, src/main/java/d83t/bpmbackend/domain/aggregate/profile/service/ProfileImageServiceImpl.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/controller/UserController.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/entity/User.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/repository/UserRepository.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserService.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImpl.java
- 카카오 로그인 API 구현
- 카카오 로그인 API를 구현하였습니다.
- 예외처리는 향후, 전역 예외처리 컨트롤러 추가후 넣겠습니다.
- 컨트롤러 테스트 진행
- 데이터베이스 확인
=> [D83T-16] 카카오 로그인 API 구현

.gitignore, build.gradle, src/main/java/d83t/bpmbackend/config/S3Config.java, src/main/java/d83t/bpmbackend/domain/aggregate/profile/service/ProfileImageServiceImpl.java, src/main/java/d83t/bpmbackend/exception/Error.java
- S3 이미지 업로드 구현
- S3 이미지 업로드 구현
=> [D83T-26] S3업로드 서비스 구현

src/main/java/d83t/bpmbackend/domain/aggregate/community/controller/BodyShapeController.java, src/main/java/d83t/bpmbackend/domain/aggregate/community/dto/BodyShapeResponse.java, src/main/java/d83t/bpmbackend/domain/aggregate/community/repository/BodyShapeRepository.java, src/main/java/d83t/bpmbackend/domain/aggregate/community/service/BodyShapeService.java, src/main/java/d83t/bpmbackend/domain/aggregate/community/service/BodyShapeServiceImpl.java
- 내 눈바디 기록하기 리스트 조회 API 구현
- 내 눈바디 기록하기 최초 조회시 보여주는 내 눈바디 포스트 리스트들입니다.
- postman
=> [D83T-37] 내 눈바디 기록하기 리스트 조회 API 구현

src/main/java/d83t/bpmbackend/domain/aggregate/location/controller/LocationController.java, src/main/java/d83t/bpmbackend/domain/aggregate/location/dto/LocationRequestDto.java, src/main/java/d83t/bpmbackend/domain/aggregate/location/dto/LocationResponseDto.java, src/main/java/d83t/bpmbackend/domain/aggregate/location/entity/Location.java, src/main/java/d83t/bpmbackend/domain/aggregate/location/repository/LocationRepository.java, src/main/java/d83t/bpmbackend/domain/aggregate/location/service/LocationService.java, src/main/java/d83t/bpmbackend/domain/aggregate/location/service/LocationServiceImpl.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/controller/StudioController.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/StudioCreateRequestDto.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/StudioDto.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/Studio.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/StudioImage.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/repository/StudioRepository.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/StudioService.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/StudioServiceImpl.java, src/main/java/d83t/bpmbackend/exception/Error.java
- 위치 등록하기 API
- 스튜디오 등록하기 API
- 상세페이지에 있는 추천 순위 로직 구현과 함께 추가하기 위해 스튜디오에서 추천 필드를 제외하고 구현했습니다
- 추천 기능에 대한 구현이 필요합니다
=> [D83T-42] 위치 등록 API 및 스튜디오 등록 API 구현

src/main/java/d83t/bpmbackend/domain/aggregate/location/dto/LocationResponseDto.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/controller/StudioController.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/StudioCreateRequestDto.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/StudioResponseDto.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/Studio.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/StudioService.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/StudioServiceImpl.java
- 상세 페이지 조회 API
- 상세 페이지 조회 API 구현
- StudioResponseDto 수정
- 지역 태그 수정
=> [D83T-43] 상세 페이지 조회 API

src/main/java/d83t/bpmbackend/domain/aggregate/profile/dto/ProfileRequest.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/controller/UserController.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/dto/UserRequestDto.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserService.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImpl.java
- SignUp API 리팩터링 하였습니다.
- 추후 테스트코드 재작성 해야합니다.
- swagger관련 문서도 수정하였습니다.
=> [D83T-49] SignUp API 리팩터링 docs 수정

src/main/java/d83t/bpmbackend/domain/aggregate/profile/dto/ProfileRequest.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/controller/UserController.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserService.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImpl.java
- signUp부분 request 수정
- 가독성을 위해 하나의 객체 안에 담음
=> [D83T-49] signUp부분 request 수정

src/main/java/d83t/bpmbackend/domain/aggregate/profile/dto/ProfileRequest.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/controller/UserController.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserService.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImpl.java
=> [D83T-49] request 원복

src/main/java/d83t/bpmbackend/domain/aggregate/profile/service/ProfileImageServiceImpl.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/controller/UserController.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImpl.java, src/main/java/d83t/bpmbackend/s3/S3UploaderService.java, src/main/java/d83t/bpmbackend/s3/S3UploaderServiceImpl.java
- S3 이미지 경로를 반환하도록 수정, uuid비교 로직 수정
- S3 이미지 넣으면 풀 패스를 반환하도록 수정
=> [D83T-49] S3 이미지 경로를 반환하도록 수정, uuid비교 로직 수정

src/main/java/d83t/bpmbackend/domain/aggregate/user/controller/UserController.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/entity/Schedule.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/entity/User.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/repository/ScheduleRepository.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserService.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImpl.java, src/main/java/d83t/bpmbackend/exception/Error.java, src/test/java/d83t/bpmbackend/domain/aggregate/user/controller/UserControllerTest.java, src/test/java/d83t/bpmbackend/domain/aggregate/user/repository/ScheduleRepositoryTest.java, src/test/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImplTest.java
- 스케줄 조회 API 작성
- 스케줄 조회 API 작성하였습니다.
- 테스트코드 작성하였습니다.
코드가 점점 산으로 가는 것 같아요.
=> D83T-47 스케줄 조회 api 작성

src/main/java/d83t/bpmbackend/domain/aggregate/community/controller/BodyShapeController.java, src/main/java/d83t/bpmbackend/domain/aggregate/community/dto/BodyShapeRequest.java, src/main/java/d83t/bpmbackend/domain/aggregate/community/dto/BodyShapeResponse.java, src/main/java/d83t/bpmbackend/domain/aggregate/profile/dto/ProfileResponse.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/controller/UserController.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/dto/ScheduleRequest.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/dto/ScheduleResponse.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/dto/UserRequestDto.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserService.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImpl.java, src/test/java/d83t/bpmbackend/domain/aggregate/user/controller/UserControllerTest.java, src/test/java/d83t/bpmbackend/domain/aggregate/user/repository/ScheduleRepositoryTest.java, src/test/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImplTest.java
- 스케줄, 내눈바디 관련 docs수정
- 스케줄, 내눈바디 관련 docs수정
- 설명과 디폴트값들을 넣었습니다.
=> [D83T-50] 스케줄, 내눈바디 관련 docs수정

src/main/java/d83t/bpmbackend/domain/aggregate/location/service/LocationServiceImpl.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/controller/StudioController.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/ReviewRequestDto.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/ReviewResponseDto.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/StudioRequestDto.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/StudioResponseDto.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/Review.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/ReviewImage.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/Studio.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/repository/ReviewRepository.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/ReviewService.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/ReviewServiceImpl.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/StudioService.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/StudioServiceImpl.java, src/main/java/d83t/bpmbackend/exception/Error.java
- 리뷰 등록 API
- 리뷰 삭제 API
- 리뷰 등록 및 삭제 API 추가
- 리뷰 등록 시 스튜디오의 평균 별점 업데이트 로직 추가
=> [D83T-39] 리뷰 등록 및 삭제 API

src/main/java/d83t/bpmbackend/domain/aggregate/location/entity/Location.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/controller/StudioController.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/ReviewResponseDto.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/Review.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/ReviewImage.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/Studio.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/StudioImage.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/repository/ReviewRepository.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/ReviewService.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/ReviewServiceImpl.java
- 리뷰 상세 조회 API
- 리뷰 리스트 조회 API
- 말씀해주신 Studio 릴레이션 생성 관련하여 엔티티에 테이블명을 지정해주었습니다. 추후 다시 확인이 필요합니다!
=> [D83T-40] 리뷰 조회 API 추가

src/main/java/d83t/bpmbackend/domain/aggregate/profile/entity/Profile.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/controller/StudioController.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/ReviewResponseDto.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/Like.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/Review.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/Studio.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/repository/LikeRepository.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/repository/StudioRepository.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/LikeService.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/LikeServiceImpl.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/ReviewService.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/ReviewServiceImpl.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/StudioServiceImpl.java, src/main/java/d83t/bpmbackend/exception/Error.java
- 좋아요 등록 API
- 좋아요 삭제 API
- 리뷰 조회 시, 로그인된 유저가 각 리뷰에 좋아요를 등록했는지 아닌지 여부를 함께 반환하도록 수정했습니다.
=> [D83T-44] 리뷰 좋아요 등록 및 삭제 API

src/main/java/d83t/bpmbackend/domain/aggregate/studio/controller/StudioController.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/StudioResponseDto.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/repository/StudioRepository.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/StudioService.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/StudioServiceImpl.java, src/test/java/d83t/bpmbackend/domain/aggregate/user/repository/ScheduleRepositoryTest.java
- 스튜디오 전체 리스트 조회 API 추가
- 스튜디오 전체 리스트 조회 API 추가
- 로컬이슈로 제대로된 테스트는 못 했습니다. 해결중입니다.
=> [D83T-57] 스튜디오 전체 리스트 조회 API 추가

src/main/java/d83t/bpmbackend/domain/aggregate/studio/controller/StudioController.java
- 스튜디오 전체 리스트 조회 API 에 갯수 추가
- 스튜디오 전체 리스트 조회 API 에 갯수를 하였습니다.
=> [D83T-57] 스튜디오 전체 리스트 조회 API 에 갯수 추가

src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/ReviewRequestDto.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/ReviewResponseDto.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/StudioRequestDto.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/StudioResponseDto.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/Review.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/Studio.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/ReviewServiceImpl.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/StudioServiceImpl.java
- 추천해요 로직 추가
- 추천 칼럼 추기
- 추천해요 태그 등록
- 스튜디오 당 상위 3개의 추천 태그 반환
=> [D83T-56] 추천해요 로직 추가

src/main/java/d83t/bpmbackend/domain/aggregate/profile/dto/ProfileDto.java, src/main/java/d83t/bpmbackend/domain/aggregate/profile/service/ProfileImageService.java, src/main/java/d83t/bpmbackend/domain/aggregate/profile/service/ProfileImageServiceImpl.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/Studio.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/repository/ScheduleRepository.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/repository/UserRepository.java, src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImpl.java, src/main/java/d83t/bpmbackend/exception/Error.java
- User, Schedule관련 리팩터링
- 가독성을 위해 로직을 수정하였습니다. 
- `PostGreSQL`의 자료형에 따라 구문을 하나 수정하였습니다.
- 일정을 이미 등록한 사람은 등록 다시 못하게 막아놨습니다.
=> [D83T-64] User, Schedule관련 리팩터링, 일정 중복등록 에러 해결

src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/ReviewServiceImpl.java
- 리뷰 등록시 이미지 경로 수정
- 리뷰 등록시 이미지 경로 수정
=> hotfix: 리뷰 등록시 이미지 경로 수정

src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/LikeServiceImpl.java, src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/ReviewServiceImpl.java
- 중복 생성 이슈 해결
- Review, Like 등록 시, 중복되어 생성되는 이슈를 해결했습니다
=> hotfix: 중복 생성 이슈 수정
